-- Entfernt nicht mehr benötigte Textfelder aus produkte:
-- - datenblatt_text_2, datenblatt_text_3 (UI auf einen Block reduziert)
-- - treiber                              (Feld aus Formular entfernt)
-- - bild_detail_1_text/2_text/3_text     (Detail-Texte entfernt)
--
-- v_produkt_listing referenziert diese Spalten — daher View droppen,
-- Spalten entfernen und View ohne die Spalten neu anlegen.

DROP VIEW IF EXISTS public.v_produkt_listing;

ALTER TABLE public.produkte
  DROP COLUMN IF EXISTS datenblatt_text_2,
  DROP COLUMN IF EXISTS datenblatt_text_3,
  DROP COLUMN IF EXISTS treiber,
  DROP COLUMN IF EXISTS bild_detail_1_text,
  DROP COLUMN IF EXISTS bild_detail_2_text,
  DROP COLUMN IF EXISTS bild_detail_3_text;

CREATE VIEW public.v_produkt_listing AS
SELECT
  p.id,
  p.external_id,
  p.artikelnummer,
  p.bereich_id,
  p.kategorie_id,
  p.name,
  p.sortierung,
  p.artikel_bearbeitet,
  p.hauptbild_path,
  p.datenblatt_titel,
  p.datenblatt_text,
  p.leistung_w,
  p.nennstrom_a,
  p.nennspannung_v,
  p.schutzklasse,
  p.spannungsart,
  p.gesamteffizienz_lm_w,
  p.lichtstrom_lm,
  p.abstrahlwinkel_grad,
  p.energieeffizienzklasse,
  p.farbtemperatur_k,
  p.farbkonsistenz_sdcm,
  p.farbwiedergabeindex_cri,
  p.led_chip,
  p.lichtverteilung,
  p.ugr,
  p.masse_text,
  p.laenge_mm,
  p.breite_mm,
  p.hoehe_mm,
  p.aussendurchmesser_mm,
  p.einbaudurchmesser_mm,
  p.gewicht_g,
  p.gehaeusefarbe,
  p.montageart,
  p.schlagfestigkeit,
  p.schutzart_ip,
  p.werkstoff_gehaeuse,
  p.leuchtmittel,
  p.sockel,
  p.rollenlaenge_m,
  p.maximale_laenge_m,
  p.anzahl_led_pro_meter,
  p.abstand_led_zu_led_mm,
  p.laenge_abschnitte_mm,
  p.kleinster_biegeradius_mm,
  p.lebensdauer_h,
  p.temperatur_ta,
  p.temperatur_tc,
  p.mit_betriebsgeraet,
  p.optional_text,
  p.zertifikate,
  p.created_at,
  p.updated_at,
  p.created_by,
  p.updated_by,
  p.search_vector,
  p.datenblatt_template_id,
  p.infofeld,
  p.info_kurz,
  p.datenblatt_art,
  p.marker_info,
  p.marker_1,
  p.marker_2,
  p.marker_3,
  p.marker_preis_status,
  p.nicht_leer,
  p.sortierung_fest,
  p.sortierung_alt,
  p.sortierung_ber,
  p.kat_startseite,
  p.bild_detail_1_path,
  p.bild_detail_2_path,
  p.bild_zeichnung_1_path,
  p.bild_zeichnung_2_path,
  p.bild_zeichnung_3_path,
  p.bild_energielabel_path,
  p.marken,
  p.vollstaendig_sections,
  b.name AS bereich_name,
  k.name AS kategorie_name,
  ap.produkt_id IS NOT NULL AS hat_preis,
  ((SELECT count(*) FROM produkt_icons pi WHERE pi.produkt_id = p.id))::integer AS icon_count,
  ((SELECT count(*) FROM produkt_bilder pb WHERE pb.produkt_id = p.id))::integer AS galerie_count,
  COALESCE(mv.percent, 0) AS completeness_percent,
  COALESCE(mv.is_complete, false) AS completeness_complete
FROM produkte p
LEFT JOIN kategorien k ON k.id = p.kategorie_id
LEFT JOIN bereiche b ON b.id = k.bereich_id
LEFT JOIN aktuelle_preise_flat ap ON ap.produkt_id = p.id
LEFT JOIN mv_produkt_completeness mv ON mv.produkt_id = p.id;
